export interface BlogData {
  id: number;
  author_name: string;
  hashtags: string[]; // Array of hashtags
  published_at: string;
  blogTopic: string;
  language: string;
}

export const blogData: BlogData[] = [
  {
    id: 1,
    author_name: "Alice Smith",
    hashtags: ["#tech", "#AI"],
    published_at: "2024-12-01T10:00:00Z",
    blogTopic: "The Future of AI",
    language: "English",
  },
  {
    id: 2,
    author_name: "Bob Johnson",
    hashtags: ["#webdev", "#JavaScript"],
    published_at: "2024-12-02T09:30:00Z",
    blogTopic: "Mastering JavaScript",
    language: "English",
  },
  {
    id: 3,
    author_name: "Charlie Brown",
    hashtags: ["#health", "#nutrition"],
    published_at: "2024-11-29T08:15:00Z",
    blogTopic: "Nutrition Tips for 2024",
    language: "English",
  },
  {
    id: 4,
    author_name: "David Williams",
    hashtags: ["#design", "#UX", "#UI"],
    published_at: "2024-12-03T12:45:00Z",
    blogTopic: "UX/UI Best Practices",
    language: "English",
  },
  {
    id: 5,
    author_name: "Eva Martinez",
    hashtags: ["#marketing", "#SEO"],
    published_at: "2024-11-28T07:00:00Z",
    blogTopic: "SEO Trends in 2024",
    language: "English",
  },
  {
    id: 6,
    author_name: "Frank Wilson",
    hashtags: ["#business", "#startup"],
    published_at: "2024-12-05T14:30:00Z",
    blogTopic: "Startup Growth Strategies",
    language: "English",
  },
  {
    id: 7,
    author_name: "Grace Lee",
    hashtags: ["#innovation", "#tech"],
    published_at: "2024-11-25T10:00:00Z",
    blogTopic: "Disruptive Technologies",
    language: "English",
  },
  {
    id: 8,
    author_name: "Henry Walker",
    hashtags: ["#fitness", "#strength"],
    published_at: "2024-12-01T08:30:00Z",
    blogTopic: "Building Strength for 2024",
    language: "English",
  },
  {
    id: 9,
    author_name: "Irene Scott",
    hashtags: ["#finance", "#investment"],
    published_at: "2024-11-30T16:00:00Z",
    blogTopic: "Investing in the Stock Market",
    language: "English",
  },
  {
    id: 10,
    author_name: "Jackie Taylor",
    hashtags: ["#lifestyle", "#minimalism"],
    published_at: "2024-12-02T17:30:00Z",
    blogTopic: "Minimalist Living",
    language: "English",
  },
  {
    id: 11,
    author_name: "Kyle Harris",
    hashtags: ["#technology", "#blockchain"],
    published_at: "2024-12-04T11:00:00Z",
    blogTopic: "Blockchain Beyond Cryptocurrency",
    language: "English",
  },
  {
    id: 12,
    author_name: "Laura Clark",
    hashtags: ["#travel", "#destinations"],
    published_at: "2024-11-29T13:45:00Z",
    blogTopic: "Top Destinations for 2024",
    language: "English",
  },
  {
    id: 13,
    author_name: "Mike Rodriguez",
    hashtags: ["#music", "#genres"],
    published_at: "2024-12-05T18:00:00Z",
    blogTopic: "The Evolution of Music Genres",
    language: "English",
  },
  {
    id: 14,
    author_name: "Nancy Perez",
    hashtags: ["#cooking", "#recipes"],
    published_at: "2024-12-01T12:15:00Z",
    blogTopic: "Healthy Recipes for 2024",
    language: "English",
  },
  {
    id: 15,
    author_name: "Oscar Martinez",
    hashtags: ["#entrepreneurship", "#branding"],
    published_at: "2024-11-27T10:45:00Z",
    blogTopic: "How to Build a Strong Brand",
    language: "English",
  },
  {
    id: 16,
    author_name: "Paul Anderson",
    hashtags: ["#sustainability", "#green"],
    published_at: "2024-12-03T13:00:00Z",
    blogTopic: "Green Business Practices",
    language: "English",
  },
  {
    id: 17,
    author_name: "Quincy Moore",
    hashtags: ["#education", "#elearning"],
    published_at: "2024-12-02T10:30:00Z",
    blogTopic: "E-Learning Trends in 2024",
    language: "English",
  },
  {
    id: 18,
    author_name: "Rachel Green",
    hashtags: ["#tech", "#AI", "#healthcare"],
    published_at: "2024-12-04T15:45:00Z",
    blogTopic: "Artificial Intelligence in Healthcare",
    language: "English",
  },
  {
    id: 19,
    author_name: "Steve Allen",
    hashtags: ["#sports", "#psychology"],
    published_at: "2024-12-06T14:00:00Z",
    blogTopic: "The Impact of Sports Psychology",
    language: "English",
  },
  {
    id: 20,
    author_name: "Tina Adams",
    hashtags: ["#business", "#leadership"],
    published_at: "2024-11-28T18:00:00Z",
    blogTopic: "Navigating Business Challenges",
    language: "English",
  },
  {
    id: 21,
    author_name: "Ursula Baker",
    hashtags: ["#tech", "#quantum"],
    published_at: "2024-12-01T16:30:00Z",
    blogTopic: "Quantum Computing Explained",
    language: "English",
  },
  {
    id: 22,
    author_name: "Victor Thomas",
    hashtags: ["#leadership", "#strategy"],
    published_at: "2024-12-05T11:45:00Z",
    blogTopic: "Effective Leadership Strategies",
    language: "English",
  },
  {
    id: 23,
    author_name: "Wendy White",
    hashtags: ["#motivation", "#success"],
    published_at: "2024-12-02T12:00:00Z",
    blogTopic: "Staying Motivated in 2024",
    language: "English",
  },
  {
    id: 24,
    author_name: "Xander King",
    hashtags: ["#startup", "#growth"],
    published_at: "2024-11-30T17:15:00Z",
    blogTopic: "Tips for Starting a Business",
    language: "English",
  },
  {
    id: 25,
    author_name: "Yvonne Clark",
    hashtags: ["#tech", "#innovation"],
    published_at: "2024-12-03T10:30:00Z",
    blogTopic: "Tech Innovations to Watch",
    language: "English",
  },
  {
    id: 26,
    author_name: "Zachary Johnson",
    hashtags: ["#fitness", "#beginners"],
    published_at: "2024-12-05T09:00:00Z",
    blogTopic: "The Best Workouts for Beginners",
    language: "English",
  },
  {
    id: 27,
    author_name: "Alice Smith",
    hashtags: ["#gaming", "#tech"],
    published_at: "2024-12-01T13:00:00Z",
    blogTopic: "Gaming Trends for 2024",
    language: "English",
  },
  {
    id: 28,
    author_name: "Bob Johnson",
    hashtags: ["#education", "#onlinelearning"],
    published_at: "2024-12-02T15:00:00Z",
    blogTopic: "The Future of Online Education",
    language: "English",
  },
  {
    id: 29,
    author_name: "Charlie Brown",
    hashtags: ["#marketing", "#branding"],
    published_at: "2024-11-30T11:00:00Z",
    blogTopic: "How to Build a Personal Brand",
    language: "English",
  },
  {
    id: 30,
    author_name: "David Williams",
    hashtags: ["#travel", "#budget"],
    published_at: "2024-12-04T14:00:00Z",
    blogTopic: "Traveling the World on a Budget",
    language: "English",
  },
  {
    id: 31,
    author_name: "Eva Martinez",
    hashtags: ["#design", "#innovation"],
    published_at: "2024-12-03T08:45:00Z",
    blogTopic: "Design Thinking for Innovation",
    language: "English",
  },
  {
    id: 32,
    author_name: "Frank Wilson",
    hashtags: ["#finance", "#investment"],
    published_at: "2024-11-29T10:30:00Z",
    blogTopic: "Smart Investment Strategies",
    language: "English",
  },
  {
    id: 33,
    author_name: "Grace Lee",
    hashtags: ["#leadership", "#teamwork"],
    published_at: "2024-12-06T16:00:00Z",
    blogTopic: "Building a Strong Team Culture",
    language: "English",
  },
  {
    id: 34,
    author_name: "Henry Walker",
    hashtags: ["#entrepreneurship", "#niche"],
    published_at: "2024-12-05T12:00:00Z",
    blogTopic: "Finding Your Niche as an Entrepreneur",
    language: "English",
  },
  {
    id: 35,
    author_name: "Irene Scott",
    hashtags: ["#marketing", "#content"],
    published_at: "2024-11-27T14:30:00Z",
    blogTopic: "Content Marketing Strategies",
    language: "English",
  },
  {
    id: 36,
    author_name: "Jackie Taylor",
    hashtags: ["#fitness", "#wellness"],
    published_at: "2024-12-02T09:00:00Z",
    blogTopic: "Achieving Wellness in 2024",
    language: "English",
  },
  {
    id: 37,
    author_name: "Kyle Harris",
    hashtags: ["#tech", "#AI"],
    published_at: "2024-12-04T17:30:00Z",
    blogTopic: "AI and the Future of Work",
    language: "English",
  },
  {
    id: 38,
    author_name: "Laura Clark",
    hashtags: ["#food", "#recipes"],
    published_at: "2024-12-01T18:15:00Z",
    blogTopic: "Delicious Vegan Recipes",
    language: "English",
  },
  {
    id: 39,
    author_name: "Mike Rodriguez",
    hashtags: ["#gaming", "#AI"],
    published_at: "2024-11-30T16:30:00Z",
    blogTopic: "AI in Gaming",
    language: "English",
  },
  {
    id: 40,
    author_name: "Nancy Perez",
    hashtags: ["#lifestyle", "#selfcare"],
    published_at: "2024-11-28T13:00:00Z",
    blogTopic: "Self-Care Practices for 2024",
    language: "English",
  },
  {
    id: 41,
    author_name: "Oscar Martinez",
    hashtags: ["#marketing", "#SEO"],
    published_at: "2024-12-05T11:30:00Z",
    blogTopic: "Advanced SEO Techniques",
    language: "English",
  },
  {
    id: 42,
    author_name: "Paul Anderson",
    hashtags: ["#entrepreneurship", "#leadership"],
    published_at: "2024-12-04T13:15:00Z",
    blogTopic: "Building Leadership in Your Startup",
    language: "English",
  },
  {
    id: 43,
    author_name: "Quincy Moore",
    hashtags: ["#tech", "#blockchain"],
    published_at: "2024-12-06T11:45:00Z",
    blogTopic: "Blockchain's Role in Cybersecurity",
    language: "English",
  },
  {
    id: 44,
    author_name: "Rachel Green",
    hashtags: ["#marketing", "#branding"],
    published_at: "2024-12-01T10:15:00Z",
    blogTopic: "Branding in the Digital Age",
    language: "English",
  },
  {
    id: 45,
    author_name: "Steve Allen",
    hashtags: ["#fitness", "#strength"],
    published_at: "2024-11-30T10:30:00Z",
    blogTopic: "Strength Training Tips for 2024",
    language: "English",
  },
  {
    id: 46,
    author_name: "Tina Adams",
    hashtags: ["#business", "#leadership"],
    published_at: "2024-12-03T17:45:00Z",
    blogTopic: "Leading Through Change",
    language: "English",
  },
  {
    id: 47,
    author_name: "Ursula Baker",
    hashtags: ["#tech", "#AI"],
    published_at: "2024-11-28T14:00:00Z",
    blogTopic: "AI's Impact on Business",
    language: "English",
  },
  {
    id: 48,
    author_name: "Victor Thomas",
    hashtags: ["#fitness", "#wellness"],
    published_at: "2024-12-01T08:00:00Z",
    blogTopic: "Improving Your Mental Health in 2024",
    language: "English",
  },
  {
    id: 49,
    author_name: "Wendy White",
    hashtags: ["#leadership", "#teamwork"],
    published_at: "2024-11-27T12:30:00Z",
    blogTopic: "Effective Team Management",
    language: "English",
  },
  {
    id: 50,
    author_name: "Xander King",
    hashtags: ["#entrepreneurship", "#startup"],
    published_at: "2024-12-06T12:00:00Z",
    blogTopic: "Managing Your Startup's Growth",
    language: "English",
  },
];

export const hastags = [
  { id: 1, name: "#tech" },
  { id: 2, name: "#AI" },
  { id: 3, name: "#webdev" },
  { id: 4, name: "#JavaScript" },
  { id: 5, name: "#health" },
  { id: 6, name: "#nutrition" },
  { id: 7, name: "#design" },
  { id: 8, name: "#UX" },
  { id: 9, name: "#UI" },
  { id: 10, name: "#marketing" },
  { id: 11, name: "#SEO" },
  { id: 12, name: "#business" },
  { id: 13, name: "#startup" },
  { id: 14, name: "#innovation" },
  { id: 15, name: "#fitness" },
  { id: 16, name: "#strength" },
  { id: 17, name: "#finance" },
  { id: 18, name: "#investment" },
  { id: 19, name: "#lifestyle" },
  { id: 20, name: "#minimalism" },
  { id: 21, name: "#technology" },
  { id: 22, name: "#blockchain" },
  { id: 23, name: "#travel" },
  { id: 24, name: "#destinations" },
  { id: 25, name: "#music" },
  { id: 26, name: "#genres" },
  { id: 27, name: "#cooking" },
  { id: 28, name: "#recipes" },
  { id: 29, name: "#entrepreneurship" },
  { id: 30, name: "#branding" },
  { id: 31, name: "#sustainability" },
  { id: 32, name: "#green" },
  { id: 33, name: "#education" },
  { id: 34, name: "#elearning" },
  { id: 35, name: "#motivation" },
  { id: 36, name: "#success" },
  { id: 37, name: "#sports" },
  { id: 38, name: "#psychology" },
  { id: 39, name: "#quantum" },
  { id: 40, name: "#growth" },
  { id: 41, name: "#teamwork" },
  { id: 42, name: "#niche" },
  { id: 43, name: "#food" },
  { id: 44, name: "#wellness" },
  { id: 45, name: "#selfcare" },
];
